
name: Update Finland wastewater data
#
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '16 09 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false 
        fetch-depth: 0 
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver_manager
    - name: Run scraper
      run: python scripts/finland_get_ww_data.py
    
    - name: Commit and push CSV file
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update Finland wastewater data" --allow-empty
        git config pull.rebase false
        git fetch
        git pull      
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: "main"
        github_token: ${{ secrets.GITHUB_TOKEN }}
