# This is a workflow to automate the dataset creation of wastewater for Sweden

name: Get Sweden Wastewater Data

on:
  schedule:
    # Runs everyweek at 9:20 on Monday
    - cron: '20 09 * * 1'

jobs:
  fetch:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Get updated data
        run: |
          curl -L https://datagraphics.dckube.scilifelab.se/dataset/0ac8fa02871745048491de74e5689da9.csv --output "data/Sweden/Sweden_ww.csv"
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit --allow-empty -m "Auto-update of the data packages" -a
          git config pull.rebase false
          git fetch
          git pull      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}
